name: testicle
favicon: null
layout_spectrum: 0.32369
typography_spectrum: 1
title: blumpkins for all
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#c6c7c1'
    - '#363636'
    - '#687b89'
    - '#181914'
  brandStrength: 0.09495642548426986
  lightness: 0.3957566446624696
  saturation: 0.6019240578170866
  rhythmicContrast: 0.8748564377892762
purpose: []
