name: testicle
favicon: null
layout_spectrum: 0.32369
typography_spectrum: 1
title: blumpkins for all
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#75797a'
    - '#e3e5e4'
    - '#7cc4b9'
    - '#171918'
    - '#de373b'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
