name: testicle
favicon: null
layout_spectrum: 0.19822056754492223
typography_spectrum: 0.9859973250422627
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.09495642548426986
  lightness: 0.3957566446624696
  saturation: 0.6019240578170866
  rhythmicContrast: 0.8748564377892762
purpose: []
